version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-movie-app:/data/db

volumes:
  mongo-movie-app: