version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379"

  mongo:
    image: mongo
    ports:
      - "27017"
    volumes:
      - mongodb-movie-app:/data/db
  
  api:
    image: movie-app-api
    ports: 
      - "5000:80"
    environment:
      - NODE_ENV=production
      - API_PORT=80
      - MONGODB_CONNECTION=mongodb://mongo:27017
      - MONGODB_USER=
      - MONGODB_PASSWORD=
      - MONGODB_DATABASE=movie-app
      - MONGODB_AUTOINDEX=1
      - MONGODB_DEBUG=0
      - REDIS_CONNECTION=redis://redis:6379/0
      - JWT_SECRET_KEY=b3ceabc1b1d61c517b963f60d3dd9c0b
      - JWT_SECRET_EXPIRES=3600
      - JWT_REFRESH_SECRET_KEY=497c871700df8272be05cea619aa33af
      - JWT_REFRESH_SECRET_EXPIRES=604800
    entrypoint:
      - npm
      - run
      - production
    depends_on: 
      - redis
      - mongo

  web:
    image: movie-app-web
    ports:
      - "5001:80"
    

volumes:
  mongodb-movie-app: